### ISSUE TITLE
493 unread messages

### ISSUE THREAD

**Issue by williamsk** [ejwilburn/PalaverCore#18]
From EJ:
>  FYI it's the thread titles being lazy loaded that are seeing this and on my end it looks like only the first lazy loaded set has the problem, scroll down and load more and note in the issue whether you see more of that or not.

Yes, it appears to be the first set of thread titles that are loaded after the initial page load.  When I scroll down past those, none of them have the unread markers.  Additionally, the page title currently shows \*493\* which makes it impossible for me to know if there's actually an unread message for me to see or not until I go to the tab and look at the thread list.

**Comment by ejwilburn** [comment]
You should read those messages.

**Comment by ejwilburn** [comment]
I read them and holy crap.  I don't even know what to say.  You need help.

**Comment by ejwilburn** [comment]
Fixed with the upgrade to .NET Core 2.0 and SignalR 1.0 Alpha
