### ISSUE TITLE
Horizontal scrollbar in thread list when vertical scrollbar is visible

### ISSUE THREAD

**Issue by williamsk** [ejwilburn/PalaverCore#3]
Once the thread list gets long enough to cause a vertical scrollbar to appear, an ugly horizontal scrollbar appears that serves no purpose (you can't actually scroll it anywhere).  I'm assuming because there isn't enough margin/padding/whatever in that div to accommodate the vertical scrollbar once it appears?  <shrug>

This is a minor issue (don't see a way to set a priority in GitHub's issue tracker).

![image](https://cloud.githubusercontent.com/assets/2839146/24730610/31392db8-1a2a-11e7-86b6-59cf567c5087.png)

**Comment by ejwilburn** [comment]
It also shows for me when the vertical scrollbar isn't there, pretty sure it's the same issue.
